---
title: "NMT-seq_EB+ESC: dimensionality reduction on RNA data"
output: 
  BiocStyle::html_document: 
  fig_width: 10
  fig_height: 8
---
  
```{r load_modules, echo=FALSE, include=FALSE}
library(data.table)
library(purrr)
library(scater)
library(ggplot2)
library(ggpubr)
library(RColorBrewer)
```

```{r funcs, echo=FALSE}
# source("/Users/ricard/NMT-seq_EB+ESC/rna/differential/utils.R")
```

```{r define_opts, echo=FALSE}

## Define I/O ##
io <- list()
io$rna <- "/Users/ricard/data/NMT-seq_EB+ESC/rna/SingleCellExperiment.rds"
io$metadata.file <- "/Users/ricard/data/NMT-seq_EB+ESC/sample_metadata.txt"
io$cellcycle.file <- "/Users/ricard/data/NMT-seq_EB+ESC/rna/cell_cycle/cell_cycle_scran.txt"
io$outdir <- "/Users/ricard/data/NMT-seq_EB+ESC/rna/cell_cycle/pdf"

## Define options ##
opts <- list()

# Define which cells to use
opts$day_lineage <- c(
  
  # Day 2
  "Day2_Epiblast",
  "Day2_Primitive Streak",
  
  # Day 4/5
  "Day4_Epiblast",
  "Day4_Primitive Streak",
  "Day4_Mesoderm",
  "Day5_Epiblast",
  "Day5_Primitive Streak",
  "Day5_Mesoderm",
  
  # Day 6/7
  "Day6_Mesoderm",
  "Day6_Endoderm",
  "Day6_Blood",
  "Day7_Mesoderm",
  "Day7_Endoderm",
  "Day7_Blood"
)

opts$genotype <- c(
  "WT",
  "KO"
)

opts$cells <- fread(io$metadata.file) %>% 
  .[,day_lineage:=paste(day,lineage10x_2, sep="_")] %>%
  .[day_lineage%in%opts$day_lineage & genotype%in%opts$genotype] %>%
  .[pass_rnaQC==T,id_rna]
```

<!-- Load sample metadata -->
```{r load_metadata, echo=FALSE}
sample_metadata <- fread(io$metadata.file) %>% 
  .[,lineage:=lineage10x_2] %>%
  .[,day:=ifelse(day%in%c("Day4","Day5"),"Day45",day)] %>%
  .[,day:=ifelse(day%in%c("Day6","Day7"),"Day67",day)] %>%
  .[id_rna %in% opts$cells]
```


<!-- Load pre-computed results -->
```{r}
df <- fread(io$cellcycle.file)
```


<!-- Plot proportion of cell cycle states per lineage -->
```{r}
df <- df %>% merge(sample_metadata, by=c("id_rna"))
```

```{r}
to.plot <- df[phase2!="unknown"] %>%
  .[,sum:=.N,by=c("day","genotype")] %>%
  .[,.(prop=.N/unique(sum), N=.N), by=c("day","genotype","phase2")] %>%
  .[complete.cases(.)]

for (i in unique(to.plot$day)) {
  p <- ggpie(to.plot[day==i], "prop", label = "N", fill="phase2",
        palette = c("#00AFBB", "#E7B800", "#FC4E07"), color="black") +
    facet_wrap(~genotype, nrow=1) +
    theme(
      legend.position = "right",
      legend.title = element_blank()
    )
  pdf(sprintf("%s/pieplot_%s.pdf",io$outdir,i), width=5, height=5)
  print(p)
  dev.off()
}
```

```{r}
to.plot[,day_genotype:=paste(day,genotype,sep=" ")]

p <- ggpie(to.plot, "prop", label = "N", fill="phase2",
      palette = c("#00AFBB", "#E7B800", "#FC4E07"), color="black") +
  facet_wrap(~day_genotype, ncol=2) +
  theme(
    strip.background = element_blank(),
    legend.position = "right",
    legend.title = element_blank()
  )

pdf(sprintf("%s/pieplot.pdf",io$outdir), width=5, height=8)
print(p)
dev.off()
```

