---
title: "Gastrulation: MOFA on RNA"
output:
  BiocStyle::html_document: 
    toc: false
    fig_width: 10
    fig_height: 8
---

```{r load_modules, echo=FALSE, include=FALSE}
library(MOFA)
library(data.table)
library(purrr)
library(ggplot2)
library(scater)

matrix.please <- function(x) {
    m<-as.matrix(x[,-1])
    rownames(m)<-x[[1]]
    m
}
```

<!-- Define I/O and options -->
```{r define_opts, echo=FALSE}

## Define I/O ##
io <- list()
io$basedir <- "/Users/ricard/data/NMT-seq_EB+ESC"
io$sample.metadata <- paste0(io$basedir,"/sample_metadata.txt")
io$rna.file <- "/Users/ricard/data/NMT-seq_EB+ESC/rna/SingleCellExperiment.rds"
io$outdir <- "/Users/ricard/NMT-seq_EB+ESC/rna/mofa/out"

## Define options ##
opts <- list()

# Filtering options for RNA
opts$rna_rm.low <- T       # Remove low expressed genes
opts$rna_rm.const <- T     # Remove non-variable genes
opts$rna_min.cdr <- 0.25   # Remove genes with cellular detection rate smaller than opts$min.cdr
opts$rna_ngenes <- 1500    # maximum number of genes (filter based on variance)

# Define which cells to use
opts$culture <- c(
  # "EB_Day6",
  "EB_Day7"
)
opts$celltype.mapped <- c(
  "Mature_mesoderm",
  "Nascent_mesoderm",
  "Embryonic_endoderm"
)

opts$cells <- fread(io$sample.metadata) %>% 
  .[pass_rnaQC==T] %>%
  .[culture%in%opts$culture] %>%
  # .[celltype.mapped%in%opts$celltype.mapped] %>%
  .[,id_rna]
```


<!-- Load sample metadata -->
```{r load_metadata}
sample_metadata <- fread(io$sample.metadata) %>% 
  .[id_rna %in% opts$cells] #%>% 
  # .[,stage_lineage:=as.factor(paste(stage.mapped,celltype.mapped,sep="_"))]# %>%
  # .[celltype.mapped=="Primitive_endoderm",celltype.mapped:="Visceral_endoderm"]
```

<!-- Load RNA data -->
```{r}
# Load scater object
sce <- readRDS(io$rna.file)[,opts$cells]

# Convert to data.table
rna_dt <- exprs(sce) %>% t %>% as.data.table(keep.rownames = "id_rna") %>% 
  melt(id.vars = "id_rna", value.name = "expr", variable.name = "ens_id") %>%
  merge(rowData(sce) %>% as.data.frame(row.names = rownames(sce)) %>% tibble::rownames_to_column("ens_id") %>% .[,c("ens_id","symbol")] %>% setnames("symbol","gene"))
```

<!-- Merge data with metadata -->
```{r merge}
rna_dt <- merge(rna_dt, sample_metadata, by="id_rna")
```

<!-- Filter RNA expression data -->
```{r}
# Remove lowly expressed genes
if (opts$rna_rm.low)
    rna_dt <- rna_dt[,mean:=mean(expr),by="gene"] %>% .[mean>=1.0] %>% .[,mean:=NULL]

# Remove genes with constant expression levels and sites with constant methylation levels
if (opts$rna_rm.const)
  rna_dt <- rna_dt[,var:=var(expr),by="gene"] %>% .[var>0] %>% .[,var:=NULL]

# Filter genes with low cellular detection rate and sites with low coverage across samples
rna_dt <- rna_dt[,cdr:=sum(expr>0)/length(opts$rna_cells), by="gene"] %>% .[cdr>=opts$rna_min.cdr] %>% .[,cdr:=NULL]

# Extract top N highly variable genes
keep_hv_genes <- rna_dt[,.(var=var(expr)), by="gene"] %>% setorder(-var)  %>% head(n = opts$rna_ngenes) %>% .$gene
rna_dt <- rna_dt[gene%in%keep_hv_genes]

rna_dt <- rna_dt %>% droplevels()
```

<!-- Regress out covariates -->
```{r}
# Number of expressed genes
foo <- data.table(
  id_rna = colnames(sce),
  cdr = sce$total_features_by_counts/nrow(sce)
)
rna_dt <- rna_dt %>% merge(foo, by="id_rna") %>%
  .[,expr:=lm(formula=expr~cdr)[["residuals"]], by=c("gene")]
```

<!-- Create matrix from the data.table -->
```{r}
rna_matrix <- rna_dt[,c("gene","expr","sample")] %>%
  dcast(sample~gene, value.var="expr", drop=F) %>% matrix.please() %>% t
```

<!-- Fit MOFA model -->
```{r,}
# Create MOFAobject
MOFAobject <- createMOFAobject(list(rna=rna_matrix))

# Data processing options
DataOptions <- getDefaultDataOptions()

# Model options
ModelOptions <- getDefaultModelOptions(MOFAobject)
ModelOptions$numFactors <- 10

# Training options
TrainOptions <- getDefaultTrainOptions()
TrainOptions$maxiter <- 2000
TrainOptions$tolerance <- 0.25
TrainOptions$DropFactorThreshold <- 0.000

# Prepare MOFAobject for training
MOFAmodel <- prepareMOFA(MOFAobject, 
  DataOptions = DataOptions, 
  ModelOptions = ModelOptions, 
  TrainOptions = TrainOptions
)

# Train the model
# outfile <- paste0(io$outdir,"/model.hdf5")
outfile = tempfile()
model <- runMOFA(MOFAmodel, outfile)
```

```{r}
# model <- loadModel(paste0(io$outdir,"/hdf5/model.hdf5"))
```

```{r}
sample_metadata_filt <- sample_metadata %>% setkey(sample) %>% .[MOFA::sampleNames(model)]
```


<!-- Calculate variance explained -->
```{r}
# r2 <- calculateVarianceExplained(model)$R2PerFactor
# plotVarianceExplained(model)
```


<!-- Inspect factors -->
```{r}
p <- plotFactorScatter(
  model, 
  factors=c(1,10), 
  color_by=sample_metadata_filt$celltype.mapped.y,
  shape_by=sample_metadata_filt$phenotype
)
p
# p <- p + 
#   scale_color_manual(values=opts$colors) + 
#   labs(x=sprintf("Factor 1 (%.2f%%)",r2[1,]*100), y=sprintf("Factor 2 (%.2f%%)",r2[2,]*100)) +
#   theme(
#     axis.title = element_text(size=rel(1.2)),
#     axis.ticks = element_blank(),
#     axis.text = element_blank()
#   )

# pdf(paste0(io$outdir,"/pdf/mofa_rna.pdf"), useDingbats = F, onefile = F, width=6, height=4)
# print(p)
# dev.off()
```

```{r}
plotWeights(model, view="rna", factor=10, scale=F, nfeatures = 25)
```

```{r}
plotFactorScatter(
  model, 
  factors=c("LF1","LF2"), 
  color_by="Sox17",
  shape_by=sample_metadata_filt$culture
)
```

